include:
  #BACKEND
  - component: gitlab.com/telecom-argentina/devops/cicd/components/terraform-components/terraform-backend-generator-s3/monorepo-component@2.0.0
    inputs:
      target: "766028941436"
      target_parent_directory: "environments"
      region: us-east-2
      s3_bucket_name: sitios-wordpress-artifacts-20250328160339807200000001
      dynamodb_table: sitios-wordpress-terraform-state-lock
      role_name: terraform/sitios-wordpress-gitlab-deploy-role
      s3_bucket_key: sitios-wordpress/talentotech/terraform.tfstate
      # workspace_key_prefix: terraform/IaC/820242945253

  #PIPELINE
  - component: gitlab.com/telecom-argentina/devops/cicd/components/terraform-components/terraform-monorepo-pipeline/component@1.0.0
    inputs:
      target: "766028941436"
      target_parent_directory: "environments"
      backend_type: s3
