
include:
  #BACKEND
#  - component: gitlab.com/telecom-argentina/devops/cicd/components/terraform-components/terraform-backend-generator-s3/monorepo-component@2.0.0
  - component: $CI_SERVER_FQDN/telecom-argentina/devops/cicd/components/iac-components/terraform/s3-monorepo-backend@~latest
    inputs:
      target: "766028941436"
      target_parent_directory: "environments"
      region: us-east-2
      s3_bucket_name: sitiosweb-artifacts-20250114182119218200000001
      #dynamodb_table: sitiosweb-terraform-state-lock
      role_name: terraform/sitiosweb-gitlab-deploy-role
      s3_bucket_key: sitios-wordpress/talentotech/terraform.tfstate
      # workspace_key_prefix: terraform/IaC/820242945253
      stage: .pre
  #PIPELINE
#  - component: gitlab.com/telecom-argentina/devops/cicd/components/terraform-components/terraform-monorepo-pipeline/component@1.0.0
  - component: $CI_SERVER_FQDN/telecom-argentina/devops/cicd/components/iac-components/terraform/terraform-monorepo-component@~latest
    inputs:
      target: "766028941436"
      target_parent_directory: "environments"
      backend_type: s3
